model: # define model
  base_learning_rate: 1.0e-4
  target: seva.modules.autoencoder.LightningAutoEncoder
  params: # with all its params
    model:
      # target to instantiate object
      target: seva.modules.autoencoder.AutoEncoder
      # params:
      #   chunk_size: None
    learning_rate: 1.0e-4

# data: # load data from .py
#   target: seva.data.mvh_dataloader.MVHumanNetLoader
#   params:
#     root_dir: "/workspace/datasetvol/mvhuman_data/mv_captures"
#     batch_size: 8
#     num_workers: 2
#     shuffle: True
#     image_size: 576 # resize to 576x576 output

# data:
#   target: sgm.data.mnist.MNISTLoader
#   params:
#     batch_size: 256
#     num_workers: 2
#     prefetch_factor: 1
#     seva_local: True

data:
  target: seva.data.mvh_dataloader.MVHumanNetLoader
  params:
    root_dir: "/workspace/datasetvol/mvhuman_data/mv_captures"
    batch_size: 1
    num_workers: 1
    data_limit: 2
    image_size: 512


lightning:
  modelcheckpoint:
    params:
      every_n_train_steps: 5000

  callbacks:
    metrics_over_trainsteps_checkpoint:
      params:
        every_n_train_steps: 25000

    image_logger:
      target: main.ImageLogger
      params:
        disabled: False
        batch_frequency: 1000
        max_images: 16
        increase_log_steps: True
        log_first_step: False
        log_images_kwargs:
          use_ema_scope: False
          N: 16
          n_rows: 4

  trainer:
    devices: 0,
    benchmark: True
    num_sanity_val_steps: 0
    accumulate_grad_batches: 1
    max_epochs: 1